USE AuthDB;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'User')
BEGIN
    CREATE TABLE [User]
    (
        UserID INT PRIMARY KEY IDENTITY,
        Username NVARCHAR(50) NOT NULL,
        Email NVARCHAR(200) NOT NULL,
        PasswordHash NVARCHAR(128) NOT NULL,
        Salt NVARCHAR(128) NOT NULL
    );
END;